### ISSUE TITLE
PCB design

### ISSUE THREAD

**Issue by kochie** [unihackhq/rules#2]
I have a rule question asked by a competitor. Can they design a PCB and have it printed before the event to assemble on the day?

**Comment by hugomd** [comment]
I would think so — it'd be a bit difficult to design and print in 24 hours wouldn't it?

**Comment by kochie** [comment]
Yeah and not only that, depending on the use case, [breadboards suck](https://electronics.stackexchange.com/questions/2103/when-to-avoid-using-a-breadboard).

**Comment by terencehuynh** [comment]
I personally think we should have a platform-agnostic decision on this - so to ensure that we don't have a decision for hardware hacks and a seperate decision for software.

With regards to PCB designs itself, then I have no issue with a person designing the board, and printing it out. I also have no issue with someone bringing in a *printed* UML diagram in of what their application is meant to do.

👍 

---

As an aside, do you think we might need to clarify our definition on 'design work' to limit it to just UX and interface design cannot be done before, but other 'design' (such as PCB and UML diagrams) can be done?

**Comment by hugomd** [comment]
@terencehuynh I think it'd be good to give a specific list of things that can be done before or cannot be done before, with a simple "contact us for edge cases".

**Comment by erfanio** [comment]
So the list so far is:

- PCB Design
- Printed PCB
- UML Design

?

**Comment by terencehuynh** [comment]
I think this is it so far @erfanio. We can add more when the time comes.

@kochie @hugomd @dsykesturner @erfanio - we are happy to close and accept?

**Comment by hugomd** [comment]
@terencehuynh Yup, LGTM ✌️

**Comment by terencehuynh** [comment]
Closing.
