### ISSUE TITLE
Exception for students remotely studying overseas universities but living in aus

### ISSUE THREAD

**Issue by josiahyeow** [unihackhq/rules#6]

**Comment by terencehuynh** [comment]
As per our discussion in the leads meeting, we've all agreed to allow this exemption and change the eligibility rules to:

> Each member of a team must be 18 years or older, and be either: a student studying at an accredited university or TAFE college in Australia or New Zealand as of 2020 or 2021; or a university student currently residing in Australia or New Zealand. 

_Approved by Leads Meeting on January 10_
